Repository ssafyteam/ssafy-toy-project, pull requests merged in 2023-11, with the labels that each got.

#16 ⚡Update: 포스트 관련 엔티티 및 서비스 로직 변경
  demo/src/main/java/com/weareone/quicklog/controller/PostController.java
  demo/src/main/java/com/weareone/quicklog/dto/request/BlogPostRequest.java
  demo/src/main/java/com/weareone/quicklog/dto/request/UpdatePostRequest.java
  demo/src/main/java/com/weareone/quicklog/entity/Category.java
  demo/src/main/java/com/weareone/quicklog/entity/Image.java
  demo/src/main/java/com/weareone/quicklog/entity/Post.java
  demo/src/main/java/com/weareone/quicklog/entity/PostTag.java
  demo/src/main/java/com/weareone/quicklog/entity/Tag.java
  demo/src/main/java/com/weareone/quicklog/repository/CategoryRepository.java
  demo/src/main/java/com/weareone/quicklog/repository/ImageRepository.java
  demo/src/main/java/com/weareone/quicklog/repository/PostRepository.java
  demo/src/main/java/com/weareone/quicklog/repository/PostTagRepository.java
  demo/src/main/java/com/weareone/quicklog/repository/TagRepository.java
  demo/src/main/java/com/weareone/quicklog/service/PostService.java
  demo/src/main/java/com/weareone/quicklog/service/impl/PostServiceImpl.java
Labels: update

#17 ✨ Feat: Feed Paging 기능 추가
  demo/build.gradle
  demo/src/main/java/com/weareone/quicklog/controller/FeedController.java
  demo/src/main/java/com/weareone/quicklog/dto/image/ImageData.java
  demo/src/main/java/com/weareone/quicklog/dto/response/FeedInfoResponse.java
  demo/src/main/java/com/weareone/quicklog/dto/response/UserDtoResponse.java
  demo/src/main/java/com/weareone/quicklog/entity/Image.java
  demo/src/main/java/com/weareone/quicklog/mapper/FeedMapper.java
  demo/src/main/java/com/weareone/quicklog/repository/FeedRepository.java
  demo/src/main/java/com/weareone/quicklog/service/FeedService.java
  demo/src/main/java/com/weareone/quicklog/service/impl/FeedServiceImpl.java
  demo/src/test/java/com/weareone/quicklog/controller/FeedControllerTest.java
Labels: dasol, feature

#20 🔥 Remove: 필요없는 ImageRepsotory, DalleImage 삭제
  .classpath
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .metadata/.lock
  .metadata/.log
  .metadata/.plugins/org.eclipse.core.resources/.projects/.org.eclipse.egit.core.cmp/.location
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/history.version
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.index
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.version
  .metadata/.plugins/org.eclipse.core.resources/.root/2.tree
  .metadata/.plugins/org.eclipse.core.resources/.safetable/org.eclipse.core.resources
  .metadata/.plugins/org.eclipse.core.runtime/.settings/Docker.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.core.resources.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.e4.ui.css.swt.theme.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.e4.ui.workbench.renderers.swt.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.egit.core.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.ui.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jsch.core.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.m2e.apt.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.m2e.discovery.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.editors.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.ide.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.workbench.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.springframework.ide.eclipse.boot.dash.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.springframework.ide.eclipse.imports.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.springsource.ide.eclipse.commons.frameworks.core.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.springsource.ide.eclipse.commons.ui.prefs
  .metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
  .metadata/.plugins/org.eclipse.egit.core/.org.eclipse.egit.core.cmp/.project
  .metadata/.plugins/org.eclipse.egit.core/.org.eclipse.egit.core.cmp/.settings/org.eclipse.core.resources.prefs
  .metadata/.plugins/org.eclipse.jdt.core/assumedExternalFilesCache
  .metadata/.plugins/org.eclipse.jdt.core/externalFilesCache
  .metadata/.plugins/org.eclipse.jdt.core/javaLikeNames.txt
  .metadata/.plugins/org.eclipse.jdt.core/nonChainingJarsCache
  .metadata/.plugins/org.eclipse.jdt.core/variablesAndContainers.dat
  .metadata/.plugins/org.eclipse.jdt.ui/OpenTypeHistory.xml
  .metadata/.plugins/org.eclipse.jdt.ui/QualifiedTypeNameHistory.xml
  .metadata/.plugins/org.eclipse.jdt.ui/dialog_settings.xml
  .metadata/.plugins/org.eclipse.m2e.core/workspaceState.ser
  .metadata/.plugins/org.eclipse.pde.core/.cache/clean-cache.properties
  .metadata/.plugins/org.eclipse.tips.ide/dialog_settings.xml
  .metadata/.plugins/org.eclipse.ui.ide/dialog_settings.xml
  .metadata/.plugins/org.eclipse.ui.workbench/dialog_settings.xml
  .metadata/.plugins/org.eclipse.ui.workbench/workingsets.xml
  .metadata/version.ini
  .settings/org.eclipse.buildship.core.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.wst.common.project.facet.core.xml
  README.md
  bin/skt/weareone/mvp/demo/DemoApplication.class
  bin/skt/weareone/mvp/demo/DemoApplicationTests.class
  demo/src/main/java/com/weareone/quicklog/entity/DalleImage.java
  demo/src/main/java/com/weareone/quicklog/repository/DalleImageRepository.java
  startbootstrap-blog-post-gh-pages/assets/favicon.ico
  startbootstrap-blog-post-gh-pages/css/styles.css
  startbootstrap-blog-post-gh-pages/js/scripts.js
Labels: duplicate, dasol

#21 🐛 Fix: FeedMapper로 인한 실행 문제 해결
  demo/src/main/java/com/weareone/quicklog/controller/FeedController.java
  demo/src/main/java/com/weareone/quicklog/mapper/FeedMapper.java
  demo/src/main/java/com/weareone/quicklog/repository/FeedRepository.java
  demo/src/main/java/com/weareone/quicklog/service/impl/DalleServiceImpl.java
Labels: bug, dasol

#22 :zap: Feed 조회 Paging 로직 구현 / 기존 코드 수정
  README.md
  demo/src/main/java/com/weareone/quicklog/controller/FeedController.java
  demo/src/main/java/com/weareone/quicklog/dto/response/FeedInfoResponse.java
  demo/src/main/java/com/weareone/quicklog/dto/response/PageInfo.java
  demo/src/main/java/com/weareone/quicklog/dto/response/PostPagingDto.java
  demo/src/main/java/com/weareone/quicklog/dto/response/UserDtoResponse.java
  demo/src/main/java/com/weareone/quicklog/mapper/FeedMapper.java
  demo/src/main/java/com/weareone/quicklog/service/FeedService.java
  demo/src/main/java/com/weareone/quicklog/service/impl/FeedServiceImpl.java
  demo/src/test/java/com/weareone/quicklog/controller/FeedControllerTest.java
Labels: bug, dasol, feature

#28 ⚡ Update : Feed Paging 조회 코드 수정
  demo/build.gradle
  demo/src/main/java/com/weareone/quicklog/controller/FeedController.java
  demo/src/main/java/com/weareone/quicklog/service/FeedService.java
  demo/src/main/java/com/weareone/quicklog/service/impl/FeedServiceImpl.java
Labels: dasol, update

#29 ✨ Feat: OAuth2 인증 기능 추가
  demo/src/main/java/com/weareone/quicklog/config/SecurityConfig.java
  demo/src/main/java/com/weareone/quicklog/controller/UserController.java
  demo/src/main/java/com/weareone/quicklog/entity/Token.java
  demo/src/main/java/com/weareone/quicklog/repository/TokenRepository.java
  demo/src/main/java/com/weareone/quicklog/security/JwtAuthenticationFilter.java
  demo/src/main/java/com/weareone/quicklog/security/JwtTokenProvider.java
  demo/src/main/java/com/weareone/quicklog/security/OAuth2SuccessHandler.java
  demo/src/main/java/com/weareone/quicklog/service/UserService.java
  demo/src/main/java/com/weareone/quicklog/service/impl/UserServiceImpl.java
Labels: update
